import type { Review, ReviewComment, PullRequest } from "@prisma/client";

/**
 * Computes a letter grade from a numeric score (0-100).
 */
export function computeGrade(score: number): string {
  if (score >= 95) return "A+";
  if (score >= 85) return "A";
  if (score >= 75) return "B+";
  if (score >= 65) return "B";
  if (score >= 50) return "C";
  if (score >= 35) return "D";
  return "F";
}

const SEVERITY_EMOJI: Record<string, string> = {
  CRITICAL: "🔴",
  HIGH: "🟠",
  MEDIUM: "🟡",
  LOW: "🔵",
  INFO: "⚪",
};

const CATEGORY_LABEL: Record<string, string> = {
  BUG: "Bug",
  SECURITY: "Security",
  PERFORMANCE: "Performance",
  STYLE: "Style",
  MAINTAINABILITY: "Maintainability",
  DOCUMENTATION: "Documentation",
  TEST_COVERAGE: "Test Coverage",
  GENERAL: "General",
};

const GRADE_EMOJI: Record<string, string> = {
  "A+": "🏆",
  A: "✅",
  "B+": "👍",
  B: "📝",
  C: "⚠️",
  D: "❗",
  F: "🚨",
};

/**
 * Formats a completed review into a GitHub-compatible markdown comment.
 */
export function formatReviewForGitHub(
  review: Review & { comments: ReviewComment[] },
  _pr: Pick<PullRequest, "title" | "htmlUrl">
): string {
  const grade = review.grade ?? "N/A";
  const score = review.score?.toFixed(1) ?? "N/A";
  const gradeEmoji = GRADE_EMOJI[grade] ?? "📋";

  const sections: string[] = [
    `## 🤖 Code Review Bot`,
    ``,
    `> Automated code review powered by **Groq llama-3.3-70b-versatile**`,
    ``,
    `---`,
    ``,
    `### ${gradeEmoji} Score: **${score}/100** — Grade: **${grade}**`,
    ``,
  ];

  // Summary
  if (review.summary) {
    sections.push(`### 📋 Summary`, ``, review.summary, ``);
  }

  // Highlights (if review has raw response with highlights)
  // Note: highlights are stored in rawResponse
  let highlights: string[] = [];
  if (review.rawResponse) {
    try {
      const raw = JSON.parse(review.rawResponse) as { highlights?: string[] };
      highlights = raw.highlights ?? [];
    } catch {
      // ignore parse error
    }
  }

  if (highlights.length > 0) {
    sections.push(`### ✨ What's Good`, ``);
    highlights.forEach((h) => sections.push(`- ${h}`));
    sections.push(``);
  }

  // Issues table
  if (review.comments.length > 0) {
    sections.push(`### 🔍 Issues Found (${review.comments.length})`, ``);
    sections.push(
      `| Severity | Category | File | Line | Issue |`,
      `|---|---|---|---|---|`
    );

    const sorted = [...review.comments].sort((a, b) => {
      const order = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"];
      return order.indexOf(a.severity) - order.indexOf(b.severity);
    });

    sorted.forEach((c) => {
      const emoji = SEVERITY_EMOJI[c.severity] ?? "⚪";
      const category = CATEGORY_LABEL[c.category] ?? c.category;
      const file = c.path.split("/").pop() ?? c.path;
      const line = c.line ? `L${c.line}` : "—";
      sections.push(
        `| ${emoji} ${c.severity} | ${category} | \`${file}\` | ${line} | **${c.title}** |`
      );
    });

    sections.push(``);
  } else {
    sections.push(`### ✅ No Issues Found`, ``, `This PR looks great! No issues detected.`, ``);
  }

  // Stats
  sections.push(
    `---`,
    ``,
    `<details>`,
    `<summary>📊 Review Stats</summary>`,
    ``,
    `| Metric | Value |`,
    `|---|---|`,
    `| Model | \`claude-sonnet-4-6\` |`,
    `| Input Tokens | ${review.promptTokens ?? "N/A"} |`,
    `| Output Tokens | ${review.completionTokens ?? "N/A"} |`,
    `| Issues Found | ${review.comments.length} |`,
    ``,
    `</details>`,
    ``,
    `---`,
    `*Generated by [Code Review Bot](https://github.com) • [View Full Report](#)*`
  );

  return sections.join("\n");
}
